compute_environment: LOCAL_MACHINE
deepspeed_config:
 deepspeed_config_file: zero_stage2_config.json
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: 1234
main_training_function: main
num_machines: 1
num_processes: 6
use_cpu: false